# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}-{branch}

skip_commits:
  files:
    - README.md

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# this is how to allow failing jobs in the matrix
# set this flag to immediately finish build once one of the jobs fails
matrix:
  fast_finish: true

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - ps: Install-PackageProvider -Name NuGet -Force
  - ps: Install-Module PsScriptAnalyzer -Force

hosts:
  chocopackages.ise.com: 54.231.168.128

nuget:
  account_feed: true
  project_feed: true

#---------------------------------#
#       build configuration       #
#---------------------------------#

before_build:
  - ps: c:\projects\chocotest\Analyze-Script.ps1

# run our custom scripts instead of automatic MSBuild
build_script:
  - ps: c:\projects\chocotest\Invoke-Build.ps1

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test_script:
  - ps: c:\projects\chocotest\Invoke-Test.ps1


#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: '**\*.nupkg'
    name: nupkgFile
